import { motion } from 'framer-motion'
import { ArrowRight, CircleAlert, Clock3, Leaf, LogIn, Recycle, ShieldCheck, Star, Truck, CheckCircle2 } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { forwardRef, useEffect, useState } from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { useAuth } from './context/AuthContext'
import { api } from './services/api'
import { EmptyState, ErrorState, LoadingState } from './components/Feedback'

const statusLabels = (value) => value?.toLowerCase().replaceAll('_', ' ')
const useLoad = (request, deps = []) => {
  const [state, setState] = useState({ loading: true, error: '', data: null })
  useEffect(() => { let active = true; setState({ loading: true, error: '', data: null }); request().then(({ data }) => active && setState({ loading: false, error: '', data: data.data })).catch((e) => active && setState({ loading: false, error: e.response?.data?.message || 'Unable to load this section.', data: null })); return () => { active = false } }, deps)
  return state
}
const Button = ({ children, ...props }) => <button className="button primary" {...props}>{children}</button>
function State({ state, children }) { if (state.loading) return <LoadingState />; if (state.error) return <ErrorState message={state.error} />; return children }

export function LandingPage() {
  return <main><section className="hero container"><div className="hero-copy"><span className="eyebrow"><Leaf size={15} /> Circular economy, made local</span><h1>Waste has a journey.<br /><em>Make it count.</em></h1><p className="lede">Kabadivala connects homes, collectors, hubs and recyclers so every kilogram gets a responsible next step.</p><div className="actions"><Link className="button primary" to="/register">Start recycling <ArrowRight size={17} /></Link><Link className="button secondary" to="/login">Sign in</Link></div><div className="trust"><ShieldCheck size={18} /> Traceable handoffs · Fair rates · Local livelihoods</div></div><div className="hero-art"><div className="orb" /><div className="impact-card"><span>Built for the whole chain</span><strong>One clear journey</strong><small>From local collection to responsible recycling</small><div className="impact-bar"><i /></div></div><div className="route-card"><Recycle size={20} /><div><b>One clear chain</b><small>Home → Collector → Hub → Recycler</small></div></div></div></section><section className="section light"><div className="container section-heading"><span className="eyebrow">Why Kabadivala</span><h2>The local network behind a cleaner tomorrow.</h2><p>Book a pickup, meet a verified collector and follow every handoff.</p></div></section></main>
}

const authSchema = z.object({ email: z.string().email('Enter a valid email'), password: z.string().min(8, 'Use at least 8 characters') })
const rolePath = (role) => ({ ADMIN: '/admin/dashboard', HUB_MANAGER: '/hub/dashboard', RECYCLER: '/recycler/dashboard', COLLECTOR: '/collector/dashboard', CUSTOMER: '/customer/dashboard' }[role] || '/dashboard')
const Field = forwardRef(function Field({ label, error, ...props }, ref) { return <label className="field"><span>{label}</span><input ref={ref} {...props} />{error && <small className="form-error">{error}</small>}</label> })
function AuthCard({ title, subtitle, children }) { return <div className="auth-page"><div className="auth-brand"><Link to="/"><span className="brand-mark"><Recycle size={19} /></span><b>Kabadivala</b></Link></div><motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="auth-card"><div className="auth-heading"><span className="eyebrow">Your workspace</span><h1>{title}</h1><p>{subtitle}</p></div>{children}<div className="demo-note"><Clock3 size={15} /> Demo accounts use password <b>Demo@12345</b></div></motion.div></div> }
export function LoginPage() { const { login } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState(''); const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm({ resolver: zodResolver(authSchema) }); const submit = async (values) => { try { const result = await login(values); navigate(rolePath(result.data.user.role)) } catch (e) { setError(e.response?.data?.message || 'Unable to sign in') } }; return <AuthCard title="Welcome back" subtitle="Sign in to your Kabadivala workspace"><form onSubmit={handleSubmit(submit)}><Field label="Email" type="email" error={errors.email?.message} {...register('email')} /><Field label="Password" type="password" error={errors.password?.message} {...register('password')} />{error && <p className="form-error"><CircleAlert size={15} />{error}</p>}<button className="button primary full" disabled={isSubmitting}>{isSubmitting ? 'Signing in…' : 'Sign in'} <LogIn size={17} /></button></form><p className="switch">New to Kabadivala? <Link to="/register">Create an account</Link></p></AuthCard> }
const registerSchema = authSchema.extend({ name: z.string().min(2, 'Enter your name'), role: z.enum(['CUSTOMER', 'COLLECTOR']) })
export function RegisterPage() { const { register: createAccount } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState(''); const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm({ resolver: zodResolver(registerSchema), defaultValues: { role: 'CUSTOMER' } }); const submit = async (values) => { try { const result = await createAccount(values); navigate(result.data.user.role === 'COLLECTOR' ? '/collector/dashboard' : '/customer/dashboard') } catch (e) { setError(e.response?.data?.message || 'Unable to create account') } }; return <AuthCard title="Create your account" subtitle="Join a more responsible recycling chain"><form onSubmit={handleSubmit(submit)}><Field label="Full name" {...register('name')} error={errors.name?.message} /><Field label="Email" type="email" {...register('email')} error={errors.email?.message} /><Field label="Password" type="password" {...register('password')} error={errors.password?.message} /><label className="field"><span>I am joining as</span><select {...register('role')}><option value="CUSTOMER">Customer</option><option value="COLLECTOR">Collector</option></select></label>{error && <p className="form-error">{error}</p>}<button className="button primary full" disabled={isSubmitting}>{isSubmitting ? 'Creating…' : 'Create account'} <ArrowRight size={17} /></button></form><p className="switch">Already registered? <Link to="/login">Sign in</Link></p></AuthCard> }

function PageHeader({ eyebrow, title, copy, action }) { return <div className="page-title"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1>{copy && <p>{copy}</p>}</div>{action}</div> }
function PickupCard({ pickup }) { return <Link className="pickup-card" to={`/customer/pickups/${pickup.id}`}><div><b>{pickup.pickupCode}</b><small>{pickup.category} · {pickup.quantity} item(s)</small></div><span className={`status status-${pickup.status.toLowerCase()}`}>{statusLabels(pickup.status)}</span><small>{new Date(pickup.pickupDate).toLocaleDateString()}</small></Link> }
function CustomerDashboard() { const state = useLoad(() => api.get('/pickups')); const points = useLoad(() => api.get('/points')); return <div className="dashboard-content"><PageHeader eyebrow="Customer workspace" title="Make your next pickup count." copy="Track requests, collectors and your eco impact." action={<Link className="button primary" to="/customer/pickups/new">New pickup <ArrowRight size={16} /></Link>} /><div className="stat-grid"><div className="stat-card"><span>Active pickups</span><strong>{state.data?.pickups?.filter((p) => !['COLLECTED', 'CANCELLED', 'REJECTED'].includes(p.status)).length || 0}</strong><small>Live requests</small></div><div className="stat-card"><span>Eco points</span><strong>{points.data?.total || 0}</strong><small>Earned from collections</small></div><div className="stat-card"><span>Completed</span><strong>{state.data?.pickups?.filter((p) => p.status === 'COLLECTED').length || 0}</strong><small>Responsible handoffs</small></div></div><section className="panel"><div className="panel-heading"><h2>Recent pickups</h2><Link to="/customer/pickups">View all</Link></div><State state={state}>{state.data?.pickups?.length ? state.data.pickups.slice(0, 4).map((p) => <PickupCard pickup={p} key={p.id} />) : <EmptyState message="Your pickup journey starts here." />}</State></section></div> }
export function DashboardPage() { const { user } = useAuth(); return user?.role === 'COLLECTOR' ? <CollectorDashboard /> : <CustomerDashboard /> }

export function CustomerPickupsPage() { const state = useLoad(() => api.get('/pickups')); return <div className="dashboard-content"><PageHeader eyebrow="Customer workspace" title="My pickups" action={<Link className="button primary" to="/customer/pickups/new">New pickup</Link>} /><section className="panel"><State state={state}>{state.data?.pickups?.length ? state.data.pickups.map((p) => <PickupCard pickup={p} key={p.id} />) : <EmptyState message="No pickup requests yet." />}</State></section></div> }
export function NewPickupPage() { const navigate = useNavigate(); const [error, setError] = useState(''); const { register, handleSubmit, formState: { isSubmitting } } = useForm({ defaultValues: { quantity: 1, pickupDate: new Date().toISOString().slice(0, 10), timeSlot: '09:00 - 12:00' } }); const submit = async (values) => { try { const body = new FormData(); Object.entries(values).forEach(([key, value]) => { if (key === 'images') [...value].forEach((file) => body.append('images', file)); else if (value !== '') body.append(key, value) }); await api.post('/pickups', body, { headers: { 'Content-Type': 'multipart/form-data' } }); navigate('/customer/pickups') } catch (e) { setError(e.response?.data?.message || 'Unable to create pickup') } }; return <div className="dashboard-content narrow"><PageHeader eyebrow="New pickup" title="Tell us what you are giving a new life." copy="Images are optional. PNG, JPG and WEBP files up to 5MB each." /><form className="panel form-grid" onSubmit={handleSubmit(submit)}><label className="field"><span>Category</span><select {...register('category', { required: true })}><option value="">Choose category</option><option>Metal</option><option>Paper</option><option>Plastic</option><option>E-waste</option><option>Glass</option><option>Textile</option></select></label><Field label="Item details" placeholder="Old laptop, newspapers…" {...register('itemDetails', { required: true })} /><Field label="Brand (optional)" {...register('brand')} /><Field label="Condition" {...register('condition')} /><Field label="Quantity" type="number" min="1" {...register('quantity')} /><Field label="Estimated weight (kg)" type="number" step="0.1" {...register('estimatedWeight')} /><Field label="Address" {...register('address', { required: true })} /><Field label="Pickup date" type="date" {...register('pickupDate', { required: true })} /><label className="field"><span>Time slot</span><select {...register('timeSlot')}><option>09:00 - 12:00</option><option>12:00 - 15:00</option><option>15:00 - 18:00</option></select></label><Field label="Notes" {...register('notes')} /><label className="field"><span>Images</span><input type="file" accept="image/png,image/jpeg,image/webp" multiple {...register('images')} /></label>{error && <p className="form-error">{error}</p>}<div className="form-actions"><Link className="button secondary" to="/customer/pickups">Cancel</Link><button className="button primary" disabled={isSubmitting}>{isSubmitting ? 'Saving…' : 'Request pickup'} <ArrowRight size={16} /></button></div></form></div> }

export function PickupDetailPage() { const { id } = useParams(); const state = useLoad(() => api.get(`/pickups/${id}`), [id]); const [message, setMessage] = useState(''); const [qr, setQr] = useState(''); const transition = async (status) => { try { await api.patch(`/pickups/${id}/status`, { status }); setMessage('Status updated'); window.location.reload() } catch (e) { setMessage(e.response?.data?.message || 'Action not permitted') } }; const match = async () => { try { await api.post(`/pickups/${id}/match`); window.location.reload() } catch (e) { setMessage(e.response?.data?.message || 'Matching failed') } }; return <div className="dashboard-content"><State state={state}>{state.data?.pickup && <><PageHeader eyebrow="Pickup details" title={state.data.pickup.pickupCode} copy={`${state.data.pickup.category} · ${statusLabels(state.data.pickup.status)}`} action={<span className={`status status-${state.data.pickup.status.toLowerCase()}`}>{statusLabels(state.data.pickup.status)}</span>} /><div className="detail-grid"><section className="panel"><h2>Request summary</h2><dl className="details"><dt>Items</dt><dd>{state.data.pickup.itemDetails}</dd><dt>Address</dt><dd>{state.data.pickup.address}</dd><dt>Schedule</dt><dd>{new Date(state.data.pickup.pickupDate).toLocaleDateString()} · {state.data.pickup.timeSlot}</dd><dt>Weight</dt><dd>{state.data.pickup.estimatedWeight || '—'} kg</dd></dl><div className="form-actions">{['REQUESTED', 'REJECTED'].includes(state.data.pickup.status) && <Button onClick={match}>Find a collector</Button>}{['REQUESTED', 'MATCHING', 'ASSIGNED', 'ACCEPTED'].includes(state.data.pickup.status) && <button className="button secondary" onClick={() => transition('CANCELLED')}>Cancel</button>}</div>{message && <p className="form-error">{message}</p>}</section><section className="panel"><h2>Live timeline</h2><div className="timeline vertical">{state.data.pickup.events?.map((entry) => <div className="step" key={entry.id}><span><CheckCircle2 size={15} /></span><div><b>{statusLabels(entry.status)}</b><small>{new Date(entry.createdAt).toLocaleString()} · {entry.actor?.name || 'Kabadivala'}</small>{entry.note && <p>{entry.note}</p>}</div></div>)}</div></section></div><section className="panel qr-panel"><h2>Secure handoff QR</h2><p>Generate a replaceable verification token for the handoff.</p><Button onClick={async () => { const result = await api.get(`/pickups/${id}/qr`); setQr(result.data.data.token) }}>Generate token</Button>{qr && <code>{qr}</code>}</section></>}</State></div> }

export function ProfilePage() { const { user } = useAuth(); const [saved, setSaved] = useState(''); const { register, handleSubmit, formState: { isSubmitting } } = useForm({ defaultValues: user }); const submit = async (values) => { await api.patch('/auth/profile', { ...values, capacityKg: values.capacityKg ? Number(values.capacityKg) : null, available: values.available === true || values.available === 'true' }); setSaved('Profile saved') }; return <div className="dashboard-content narrow"><PageHeader eyebrow="Account" title="Your profile" /><form className="panel form-grid" onSubmit={handleSubmit(submit)}><Field label="Name" {...register('name')} /><Field label="Phone" {...register('phone')} /><Field label="Address" {...register('address')} /><Field label="Service area" {...register('serviceArea')} /><Field label="Supported categories" placeholder="metal,paper,plastic" {...register('supportedCategories')} /><Field label="Capacity (kg)" type="number" {...register('capacityKg')} /><div className="form-actions"><button className="button primary" disabled={isSubmitting}>Save profile</button>{saved && <span className="success-text">{saved}</span>}</div></form></div> }
export function PointsPage() { const state = useLoad(() => api.get('/points')); return <div className="dashboard-content"><PageHeader eyebrow="Impact wallet" title="Eco points" copy="10 base points + category rate per estimated kilogram after collection." /><State state={state}>{state.data && <><div className="points-hero"><Leaf size={28} /><strong>{state.data.total} points</strong></div><section className="panel">{state.data.transactions?.length ? state.data.transactions.map((t) => <div className="list-row" key={t.id}><span><b>+{t.points} points</b><small>{t.reason}</small></span><time>{new Date(t.createdAt).toLocaleDateString()}</time></div>) : <EmptyState message="Collect your first pickup to earn points." />}</section></>}</State></div> }
export function ReviewsPage() { const state = useLoad(() => api.get('/reviews')); return <div className="dashboard-content"><PageHeader eyebrow="Trust" title="Reviews" /><section className="panel"><State state={state}>{state.data?.reviews?.length ? state.data.reviews.map((r) => <div className="list-row" key={r.id}><span><b>{'★'.repeat(r.rating)}</b><small>{r.comment || 'No comment'} · {r.pickup?.pickupCode}</small></span></div>) : <EmptyState message="Reviews will appear after your collected pickups." />}</State></section></div> }
export function ComplaintsPage() { const state = useLoad(() => api.get('/complaints')); const pickups = useLoad(() => api.get('/pickups')); const [done, setDone] = useState(''); const submit = async (e) => { e.preventDefault(); const data = new FormData(e.currentTarget); await api.post('/complaints', Object.fromEntries(data)); setDone('Complaint submitted'); e.currentTarget.reset() }; return <div className="dashboard-content"><PageHeader eyebrow="Support" title="Complaints" /><form className="panel form-grid" onSubmit={submit}><label className="field"><span>Pickup</span><select name="pickupId">{pickups.data?.pickups?.map((p) => <option value={p.id} key={p.id}>{p.pickupCode}</option>)}</select></label><Field label="Subject" name="subject" required /><Field label="Description" name="description" required /><button className="button primary">Submit complaint</button>{done && <span className="success-text">{done}</span>}</form><section className="panel"><State state={state}>{state.data?.complaints?.length ? state.data.complaints.map((c) => <div className="list-row" key={c.id}><span><b>{c.subject}</b><small>{c.description}</small></span><span className="status">{c.status}</span></div>) : <EmptyState />}</State></section></div> }
export function NotificationsPage() { const state = useLoad(() => api.get('/notifications')); return <div className="dashboard-content"><PageHeader eyebrow="Updates" title="Notifications" /><section className="panel"><State state={state}>{state.data?.notifications?.length ? state.data.notifications.map((n) => <div className={`list-row ${!n.readAt ? 'unread' : ''}`} key={n.id}><span><b>{n.title}</b><small>{n.message}</small></span><time>{new Date(n.createdAt).toLocaleString()}</time></div>) : <EmptyState message="You are all caught up." />}</State></section></div> }

function CollectorDashboard() { const state = useLoad(() => api.get('/collector/requests')); return <div className="dashboard-content"><PageHeader eyebrow="Collector workspace" title="Your local collection route." copy="Accept requests and keep every handoff traceable." action={<Link className="button primary" to="/collector/requests">View requests <ArrowRight size={16} /></Link>} /><div className="stat-grid"><div className="stat-card"><span>Requests</span><strong>{state.data?.pickups?.length || 0}</strong><small>Ready to review</small></div><div className="stat-card"><span>Trust score</span><strong>5.0</strong><small><Star size={13} /> Verified profile</small></div><div className="stat-card"><span>Network</span><strong>Local</strong><small>Fair, visible work</small></div></div><section className="panel"><h2>Next requests</h2><State state={state}>{state.data?.pickups?.slice(0, 4).map((p) => <CollectorRequest key={p.id} pickup={p} />) || <EmptyState message="No requests right now." />}</State></section></div> }
function CollectorRequest({ pickup }) { const accept = async () => { await api.post(`/collector/requests/${pickup.id}/accept`); window.location.reload() }; return <div className="pickup-card"><div><b>{pickup.pickupCode}</b><small>{pickup.category} · {pickup.address || pickup.customer?.address}</small></div><span className={`status status-${pickup.status.toLowerCase()}`}>{statusLabels(pickup.status)}</span>{['REQUESTED', 'MATCHING', 'ASSIGNED'].includes(pickup.status) && <button className="button primary small" onClick={accept}>Accept</button>}<Link className="button secondary small" to={`/collector/requests/${pickup.id}`}>Details</Link></div> }
export function CollectorRequestsPage() { const state = useLoad(() => api.get('/collector/requests')); return <div className="dashboard-content"><PageHeader eyebrow="Collector workspace" title="Pickup requests" /><section className="panel"><State state={state}>{state.data?.pickups?.length ? state.data.pickups.map((p) => <CollectorRequest key={p.id} pickup={p} />) : <EmptyState message="No requests match your route." />}</State></section></div> }
export function CollectorDetailPage() { const { id } = useParams(); const state = useLoad(() => api.get(`/pickups/${id}`), [id]); const [message, setMessage] = useState(''); const advance = async (status) => { try { await api.patch(`/pickups/${id}/status`, { status }); window.location.reload() } catch (e) { setMessage(e.response?.data?.message || 'Action not permitted') } }; const collect = async (e) => { e.preventDefault(); const form = new FormData(e.currentTarget); try { await api.patch(`/collector/requests/${id}/collection`, form, { headers: { 'Content-Type': 'multipart/form-data' } }); window.location.reload() } catch (error) { setMessage(error.response?.data?.message || 'Unable to record collection') } }; return <div className="dashboard-content"><State state={state}>{state.data?.pickup && <><PageHeader eyebrow="Collector request" title={state.data.pickup.pickupCode} /><section className="panel"><dl className="details"><dt>Customer</dt><dd>{state.data.pickup.customer?.name}</dd><dt>Address</dt><dd>{state.data.pickup.address}</dd><dt>Items</dt><dd>{state.data.pickup.itemDetails}</dd></dl><div className="form-actions">{({ ASSIGNED: 'ACCEPTED', ACCEPTED: 'COLLECTOR_ON_THE_WAY', COLLECTOR_ON_THE_WAY: 'ARRIVED' })[state.data.pickup.status] && <Button onClick={() => advance(({ ASSIGNED: 'ACCEPTED', ACCEPTED: 'COLLECTOR_ON_THE_WAY', COLLECTOR_ON_THE_WAY: 'ARRIVED' })[state.data.pickup.status])}>Advance status</Button>}</div>{state.data.pickup.status === 'ARRIVED' && <form className="form-actions" onSubmit={collect}><label className="field"><span>Actual weight (kg)</span><input name="actualWeight" type="number" min="0.1" step="0.1" required /></label><label className="field"><span>Collection proof (optional)</span><input name="proof" type="file" accept="image/png,image/jpeg,image/webp" /></label><Button>Record collection</Button></form>}{message && <p className="form-error">{message}</p>}</section><section className="panel"><h2>Timeline</h2><div className="timeline vertical">{state.data.pickup.events?.map((e) => <div className="step" key={e.id}><span><Truck size={15} /></span><div><b>{statusLabels(e.status)}</b><small>{new Date(e.createdAt).toLocaleString()}</small><p>{e.note}</p></div></div>)}</div></section></>}</State></div> }
export function CollectorHistoryPage() { const state = useLoad(() => api.get('/collector/history')); return <div className="dashboard-content"><PageHeader eyebrow="Collector workspace" title="Collection history" /><section className="panel"><State state={state}>{state.data?.pickups?.length ? state.data.pickups.map((p) => <CollectorRequest pickup={p} key={p.id} />) : <EmptyState />}</State></section></div> }
export function CollectorAvailabilityPage() { const { user } = useAuth(); const [available, setAvailable] = useState(user?.available ?? true); return <div className="dashboard-content narrow"><PageHeader eyebrow="Collector workspace" title="Availability" /><section className="panel availability"><Truck size={34} /><h2>Receive nearby requests</h2><p>Smart matching uses your availability, service area, categories, capacity, distance, rating and workload.</p><button className={`toggle ${available ? 'on' : ''}`} onClick={() => { const next = !available; setAvailable(next); api.patch('/collector/availability', { available: next }) }}>{available ? 'Available' : 'Paused'}</button></section></div> }
export function CollectorRatingsPage() { const state = useLoad(() => api.get('/reviews')); return <div className="dashboard-content"><PageHeader eyebrow="Collector workspace" title="Ratings" /><section className="panel"><State state={state}>{state.data?.reviews?.length ? state.data.reviews.map((r) => <div className="list-row" key={r.id}><span><b>{'★'.repeat(r.rating)}</b><small>{r.comment || 'Customer left no comment'}</small></span></div>) : <EmptyState message="Ratings arrive after completed pickups." />}</State></section></div> }
export function NotFoundPage() { return <div className="screen-state"><h1>Page not found</h1><Link to="/">Return home</Link></div> }
export function ForbiddenPage() { return <div className="screen-state"><h1>Access restricted</h1><p>This workspace is not available for your role.</p><Link to="/dashboard">Go to dashboard</Link></div> }
